### ISSUE TITLE
Create phylotree visualization plugin

### ISSUE THREAD

**Issue by stevenweaver** [veg/tools-iuc#45]
Create a visualization plugin of [phlotree.js](https://github.com/veg/phylotree.js/tree/master) for galaxy. The [hivtrace](https://github.com/galaxyproject/galaxy/pull/5869) viz could serve as a useful starting point. You can also see me for the `mmvc` visualization, but it is not PR ready until we follow up with Sam on the supported way to pass multiple datasets to a viz.

**Comment by guerler** [comment]
Hey @stevenweaver, I added a data selector to the Galaxy object, see: https://github.com/galaxyproject/galaxy/pull/6195. Its still very basic but if it turns out to be useful we can incrementally improve it by adding datatype filters, search fields and so on. Ideally we can use it to 'replace' the browser's upload dialog in your visualization and select multiple Galaxy datasets instead.

**Comment by rdvelazquez** [comment]
The branch selection viz is [done](https://github.com/veg/galaxy/commit/8d604fbe70e00a0e4998508e5a5f11fc55abae24), we just need @guerler 's [work](https://github.com/galaxyproject/galaxy/commit/4960e08d2ab285e8d02f8498d773a393198a7e01), which is in 19.01 but not 18.09, to use it (i.e. to be able to save the annotated tree as a new history dataset). We will add the branch selection viz to galaxy.hyphy.org once 19.01 is released and we upgrade.

**Comment by rdvelazquez** [comment]
This isn't a tools-iuc issue so it's being tracked here: https://github.com/veg/galaxy/issues/7
